//----------------------------------------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="MarcusMedinapro">
// Copyright (c) MarcusMedinaPro. All rights reserved.
// </copyright>
//----------------------------------------------------------------------------------------------------------------
// This file is subject to the terms and conditions defined in file 'license.txt', which is part of this project.
// For more information visit http://MarcusMedina.Pro
//----------------------------------------------------------------------------------------------------------------
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
//----------------------------------------------------------------------------------------------------------------

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "Annoying stuff", Scope = "member", Target = "~M:TopWinPrio.MainForm.TimerTopWindowCheck_Tick(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Annoying stuff", Scope = "member", Target = "~M:TopWinPrio.MainForm.BtnClose_Click(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Annoying stuff", Scope = "member", Target = "~M:TopWinPrio.MainForm.FrmPrio_Activated(System.Object,System.EventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "Annoying stuff", Scope = "member", Target = "~M:TopWinPrio.MainForm.InitializeComponent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Annoying stuff", Scope = "member", Target = "~M:TopWinPrio.MainForm.InitializeComponent")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Annoying stuff", Scope = "member", Target = "~M:TopWinPrio.MainForm.HsbTimer_Scroll(System.Object,System.Windows.Forms.ScrollEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Justification = "This is weird")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Prio", Justification = "Annoying stuff")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Prio", Scope = "namespace", Target = "TopWinPrio", Justification = "Prio is correct for this project")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "LunaWorX", Scope = "member", Target = "TopWinPrio.MainForm.#BtnClose_Click(System.Object,System.EventArgs)", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "LunaWorX", Scope = "member", Target = "TopWinPrio.MainForm.#FrmPrio_Activated(System.Object,System.EventArgs)", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "LunaWorX", Scope = "member", Target = "TopWinPrio.MainForm.#InitializeComponent()", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "MarcusMedinaPro", Scope = "member", Target = "TopWinPrio.MainForm.#BtnClose_Click(System.Object,System.EventArgs)", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "MarcusMedinaPro", Scope = "member", Target = "TopWinPrio.MainForm.#FrmPrio_Activated(System.Object,System.EventArgs)", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "MarcusMedinaPro", Scope = "member", Target = "TopWinPrio.MainForm.#InitializeComponent()", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "prio", Scope = "member", Target = "TopWinPrio.MainForm.#InitializeComponent()", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "prioList", Scope = "member", Target = "TopWinPrio.MainForm.#InitializeComponent()", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "secs", Scope = "member", Target = "TopWinPrio.MainForm.#HsbTimer_Scroll(System.Object,System.Windows.Forms.ScrollEventArgs)", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "secs", Scope = "member", Target = "TopWinPrio.MainForm.#InitializeComponent()", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TopWinPrio", Scope = "member", Target = "TopWinPrio.MainForm.#BtnClose_Click(System.Object,System.EventArgs)", Justification = "This is just silly")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TopWinPrio", Scope = "member", Target = "TopWinPrio.MainForm.#FrmPrio_Activated(System.Object,System.EventArgs)", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly", MessageId = "TopWinPrio", Scope = "member", Target = "TopWinPrio.MainForm.#InitializeComponent()", Justification = "No worries, the compiler is just overreacting")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "TopWinPrio.NativeMethods.GetWindowThreadProcessId(System.IntPtr,System.UInt32@)", Scope = "member", Target = "TopWinPrio.NativeMethods.#GetTopWindowProcessID", Justification = "Annoying stuff")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "Annoying stuff", Scope = "member", Target = "~P:TopWinPrio.NativeMethods.GetTopWindowProcessID")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2010:Always consume the value returned by methods marked with PreserveSigAttribute", Justification = "Annoying stuff", Scope = "member", Target = "~P:TopWinPrio.NativeMethods.GetTopWindowProcessID")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1636:File header copyright text should match", Justification = "Because it's annoying")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1636:File header copyright text should match", Justification = "Freaking annoying", Scope = "namespace", Target = "~N:TopWinPrio")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1636:File header copyright text should match", Justification = "Just annoying", Scope = "namespace", Target = "~N:TopWinPrio.Properties")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1641:File header company name text should match", Justification = "Because it's annoying")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1641:File header company name text should match", Justification = "Just annoying", Scope = "namespace", Target = "~N:TopWinPrio")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1641:File header company name text should match", Justification = "Just annoying", Scope = "namespace", Target = "~N:TopWinPrio.Properties")]
